### ISSUE TITLE
npm fail

### ISSUE THREAD

**Issue by antonilol** [vzhou842/example-.io-game#10]
can someone please help me

i copied my terminal emulator below

```
pi@raspberry:~$ git clone https://github.com/vzhou842/example-.io-game.git
Cloning into 'example-.io-game'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 632 (delta 0), reused 0 (delta 0), pack-reused 629
Receiving objects: 100% (632/632), 404.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (338/338), done.
pi@raspberry:~$ cd example-.io-game/
pi@raspberry:~/example-.io-game$ npm install
(node:6808) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN package.json io-game-from-scratch@1.0.0 No repository field.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.19.66-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/example-.io-game
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/example-.io-game/npm-debug.log
npm ERR! not ok code 0
```

**Comment by antonilol** [comment]
here is the debug log
[npm-debug.log](https://github.com/vzhou842/example-.io-game/files/4031625/npm-debug.log)

**Comment by antonilol** [comment]
oops my fault 
i reinstalled node and npm and now it works
